Remove default values for vectors because GCC can't handle it
SWIG takes this code and writes:

  std::vector< nupic::UInt > arg2 = (std::vector< nupic::UInt >) {

  }

GCC fails with error:

  error: expected primary-expression before ‘)’ token

So maybe GCC is trying to use the expression in the parens as an
initializer list, rather than parsing it as a cast.